-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 15:54:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Cod_Cliente` INT NOT NULL COMMENT 'esse campo mostra o codigo do cliente',
  `Nome_cliente` VARCHAR(50) NULL COMMENT 'esse campo mostra o nome do cliente cadastrado ',
  `endereço` VARCHAR(50) NULL COMMENT 'esse campo mostra o endereço que o cliente colocar',
  `cidade` VARCHAR(50) NULL COMMENT 'esse campo mostra a cidade que o cliente mora',
  `cep` VARCHAR(10) NULL COMMENT 'esse campo mostra o codigo de endereçamento postal do cliente',
  `cnpj` VARCHAR(30) NULL COMMENT 'esse campo mostra o cadastro nacional do cliente juriidca',
  `uf` CHAR(10) NULL COMMENT 'esse campo mostra a undade de federação do cliente',
  `ie` INT(10) NULL COMMENT 'esse campo mostra a inscrição estadual do cliente',
  PRIMARY KEY (`Cod_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor` (
  `Cod_Vendedor` INT NOT NULL COMMENT 'esse campo mostra o codigo do vendedor',
  `Nome_vendedor` VARCHAR(50) NULL COMMENT 'esse campo mostra o nome do vendedor sugerido',
  `sal_fixo` DECIMAL(15,2) NULL COMMENT 'esse campo mostra o salario  fixo que o vendedor ira reveber',
  `faixa_comissao` CHAR(2) CHARACTER SET 'armscii8' NULL COMMENT 'esse campo mostra a faixa da comissao que o vendedor tem',
  PRIMARY KEY (`Cod_Vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `Num_pedido` INT NOT NULL COMMENT 'esse campo mostra o numero do pedido',
  `prazo_entrega` INT(10) NULL COMMENT 'esse campo mostra o prazo de entrega do produto',
  `Cliente_Cod_Cliente` INT NOT NULL COMMENT 'esse campo mostra o codigo do cliente',
  `Vendedor_Cod_Vendedor` INT NOT NULL COMMENT 'esse campo mostra o codigo do vendedor',
  PRIMARY KEY (`Num_pedido`, `Cliente_Cod_Cliente`, `Vendedor_Cod_Vendedor`),
  INDEX `fk_pedido_Cliente_idx` (`Cliente_Cod_Cliente` ASC) VISIBLE,
  INDEX `fk_pedido_Vendedor1_idx` (`Vendedor_Cod_Vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_Cliente`
    FOREIGN KEY (`Cliente_Cod_Cliente`)
    REFERENCES `mydb`.`Cliente` (`Cod_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_Vendedor1`
    FOREIGN KEY (`Vendedor_Cod_Vendedor`)
    REFERENCES `mydb`.`Vendedor` (`Cod_Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Poduto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Poduto` (
  `Cod_Produto` INT NOT NULL COMMENT 'esse campo mostra o codigo do produto',
  `unida_produto` VARCHAR(10) NULL COMMENT 'esse campo mostra a unidade do produto',
  `desc_produto` VARCHAR(50) NULL COMMENT 'esse campo mostra a descrição do produto',
  `valor_unit` DECIMAL(15,2) NULL COMMENT 'esse campo mostra o valor da unit',
  PRIMARY KEY (`Cod_Produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_has_Poduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_has_Poduto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_has_Poduto` (
  `pedido_Num_pedido` INT NOT NULL COMMENT 'esse campo mostra o numero do pedido',
  `Poduto_Cod_Produto` INT NOT NULL COMMENT 'esse campo mostra o codigo do produto',
  `QTDE` VARCHAR(45) NULL COMMENT 'esse campo mostra a quantidade do produto',
  PRIMARY KEY (`pedido_Num_pedido`, `Poduto_Cod_Produto`),
  INDEX `fk_pedido_has_Poduto_Poduto1_idx` (`Poduto_Cod_Produto` ASC) VISIBLE,
  INDEX `fk_pedido_has_Poduto_pedido1_idx` (`pedido_Num_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_Poduto_pedido1`
    FOREIGN KEY (`pedido_Num_pedido`)
    REFERENCES `mydb`.`pedido` (`Num_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_Poduto_Poduto1`
    FOREIGN KEY (`Poduto_Cod_Produto`)
    REFERENCES `mydb`.`Poduto` (`Cod_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
